# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Bear Cub"
license = "MIT"
licenselink = "https://github.com/clente/hugo-bearcub/blob/master/LICENSE"
description = "A Hugo theme based on »Hugo Bear Blog«. Free, extra-light, super-fast blogging."
homepage = "https://github.com/clente/hugo-bearcub"
tags = ["blog", "responsive", "minimal", "seo", "clean", "simple", "light", "minimalist", "mobile", "fast", "reading"]
features = ["favicon", "seo", "no stylesheets", "no javascript", "rss"]
min_version = "0.110.0"

# If the theme has a single author
[author]
    name = "Caio Lente"
    homepage = "https://lente.dev"

# If porting an existing theme
[original]
    author = "Jan Raasch"
    homepage = "https://www.janraasch.com"
    repo = "https://github.com/janraasch/hugo-bearblog"
