# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://example.com"

# The name of this wonderful theme ;-).
theme = "hugo-bearcub"

# Basic metadata configuration for your blog.
author = "John Doe"
copyright = "John Doe (CC BY-SA 4.0)"

# highlighting without inline styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "Example Site"
    languageName = "English 🇺🇸"
    LanguageCode = "en-US"
    contentDir = "content"
    weight = 1
    [languages.en.params]
      # You can use markdown here if you want to link somewhere
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
  [languages.pt]
    title = "Site Exemplo"
    languageName = "Português 🇧🇷"
    LanguageCode = "pt-BR"
    contentDir = "content.pt"
    weight = 2
    [languages.pt.params]
      # You can use markdown here if you want to link somewhere
      madeWith = "Feito com [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Bear Cub Demo"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["/images/share.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Example Site"

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "2006-01-02"

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
  hideUntranslated = false

  # Email
  email = "me@example.com"
